// Generated by scripts/publish.mjs from the article vault. Edit the vault, not this file.
export const topics = [
  {"id":"web","name":"Web","subs":[{"id":"security","name":"安全"}]},
];

export const articles = [
  {"id":"web-crypto","title":"浏览器中的加密与解密","topic":"web/security","date":"2026-09-23","summary":"到底如何在静态网页完成秘密内容","minutes":35,"links":[],"math":true,"mermaid":true},
];
